version: '3.8'

services:
  virtual-try-on:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-try-on-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - virtual-try-on-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: virtual-try-on-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - virtual-try-on
    restart: unless-stopped
    networks:
      - virtual-try-on-network
    profiles:
      - production

networks:
  virtual-try-on-network:
    driver: bridge

volumes:
  app_data:
    driver: local 